#!/usr/bin/env bash
# Open the /etc/passwd file for reading

exec 3< /etc/passwd

# Loop through each line of the file
while read -u 3 line
do
  # Extract the username, user id, and home directory path for each user
  username=$(echo "$line" | cut -d: -f1)
  uid=$(echo "$line" | cut -d: -f3)
  home=$(echo "$line" | cut -d: -f6)
  
  # Display the extracted information
   echo "$username:$uid:$home"
done

# Close the file descriptor for /etc/passwd
exec 3<&-

